### ISSUE TITLE
Issues with compiling against ibwxgtk3.0-dev version 3.0.2-1

### ISSUE THREAD

**Issue by majorgearhead** [dl5di/OpenDV#105]
This may have been introduced earlier, but after an update of my Raspian OS when I compile the repeater, I get a lot of these types of messages:

    /usr/include/wx-3.0/wx/list.h:205:154: warning: null character(s) ignored
             compatibility_iterator GetNext() conct  "   "                   $ \     $      {    $          (                                           "     \                iterator h = o_hter;!  (   `          � (        0 (          \

OS / Kernel Versions are as follows: 
    Operating System: Raspbian GNU/Linux 8 (jessie)
                Kernel: Linux 4.4.13-v7+
                Architecture: arm

**Comment by johnhays** [comment]
Or you can get precompiled versions --

*cd /etc/apt/sources.list.d*
*sudo mv opendv.list opendv.old*
edit (vi or nano) *compass.list,* insert this line and save

*deb [arch=armhf,amd64] http://archive.compasslinux.org/
<http://archive.compasslinux.org/> alder main*

Then execute

*curl http://archive.compasslinux.org/compass.gpg.key
<http://archive.compasslinux.org/compass.gpg.key> | sudo apt-key add -*

*sudo apt-get update*

*sudo apt-get upgrade*

*sudo apt-get install ircddbgateway ircddbgatewayd dstarrepeater
dstarrepeaterd*

On Fri, Aug 5, 2016 at 9:47 AM, William Clark <notifications@github.com>
wrote:

> This may have been introduced earlier, but after an update of my Raspian
> OS when I compile the repeater, I get a lot of these types of messages:
>
> /usr/include/wx-3.0/wx/list.h:205:154: warning: null character(s) ignored
>          compatibility_iterator GetNext() conct  "   "                   $ \     $      {    $          (                                           "     \                iterator h = o_hter;!  (   `          � (        0 (          \
>
> OS / Kernel Versions are as follows:
> Operating System: Raspbian GNU/Linux 8 (jessie)
> Kernel: Linux 4.4.13-v7+
> Architecture: arm
>
>
> --

------------------------------
John D. Hays
K7VE

PO Box 1223, Edmonds, WA 98020-1223
   <http://k7ve.org/blog>  <http://twitter.com/#!/john_hays>

**Comment by majorgearhead** [comment]
Thanks for the info.  I may do that.  But the tinkerer in me likes to compile from latest source.  Bleeding edge.

The issue looks to be with malformed chars in wx3.0-headers.  Going to sleuth around and compare versions to see when it was introduced.  This looks innocuous though.  Bet it will still compile if I let it go.  Just wondering if you guys have seen this as well with this particular version.

**Comment by majorgearhead** [comment]
I am going to close this.  Turns out just corrupted package.  I did `apt-get --reinstall install wx3.0-headers` which returned a the list.h file with no corruption.  All is well now.
