### ISSUE TITLE
dstarrepeater w/DVAP locks in transmit

### ISSUE THREAD

**Issue by K2DLS** [dl5di/OpenDV#117]
I've been using dstarrepeater/ircddbgateway running in the background with a 2 meter DVAP.  If I leave it on a quiet reflector it stays up for days at a time.  If I monitor REF001C, a very busy reflector, it will crash in less than a day and leave the DVAP stuck on transmit.  I validated the behavior on both an RPi 3 as well as a 4 core Atom processor.  To determine if I have any issue with the DVAP, I switched over to the Dutch Star condv software to test.  It stays up indefinitely while monitoring REF001C.  There's nothing in the logs with regard to the failure.  I'm willing to assist further in testing/debugging if someone can take a look at this.  I'd like to be able to return to using dstarrepeater.  DVAP firmware is 1.5.

**Comment by K2IE** [comment]
This seems to be unique to the 2 meter DVAP based upon reports.  I was running firmware 1.5 and upgraded to version 1.7.  The issue has disappeared.  Closing ticket.

**Comment by vk4tux** [comment]
Do you still have the FW versions avail on server ?

-----Original Message-----

**Comment by K2IE** [comment]
The firmware is available here: http://www.dutch-star.eu/software/

I also saw a Sourceforge page with the software, but I did not try it from this site:

https://sourceforge.net/projects/dvaputil/files/

Please only perform this update if you are confident that you know what you are doing and are willing to risk bricking your device. While I had no such issue I cannot guarantee your success.

**Comment by vk4tux** [comment]
The firmware is not available there unless you have a product license
registered on your login.re wndv

Can you share what you have please ?

-----Original Message-----

**Comment by vk4tux** [comment]
Firmware

You must have at least one active license in your account before you can
download any firmware. 


Can you share the fw files please ?


-----Original Message-----

**Comment by K2IE** [comment]
You may have missed the Create A New Account link:

http://www.dutch-star.eu/my/newacct.aspx

73

**Comment by vk4tux** [comment]
I have an account and logged in, however FW is not available unless you
have a product registered.

-----Original Message-----

**Comment by K2IE** [comment]
I do not have a product registered and I was able to download the software.
I provided an alternate source.
I am not going to add the file here because it is not mine, I do not know the licensing, and have provided 2 different ways of getting it.

**Comment by vk4tux** [comment]
I was logged in but get ;


Firmware

You must have at least one active license in your account before you can
download any firmware. 


There is no dvap FW at ;
https://sourceforge.net/projects/dvaputil/files/


So neither link provides FW for me.

**Comment by vk4tux** [comment]
The versions referred to are actually 1.05 and 1.07

-----Original Message-----

**Comment by vk4tux** [comment]
Well you did not mind not checking dutchdstar for any licensing for the
FW before you downloaded it  re 1.07?

Here is the answer we were looking for ;

http://vk4tux.duckdns.org/dvap_firmware/

-----Original Message-----
