### ISSUE TITLE
dstarrepeaterd missing

### ISSUE THREAD

**Issue by vk4tux** [dl5di/OpenDV#121]
dstarrepeaterd should be included in standard DStarRepeater make, why not ?

The capacity to have both GUI and daemon in one install as we did with wx2.8, is a big advantage, and of no disadvantage ?  also Why is 'DEBUG' in the GUI in ircddbgateway ? > FUGLY

**Comment by g4klx** [comment]
DEBUG appears in the GUI if it is a Debug build. The amount of logging changes and certain other differences. It is useful to know.

**Comment by vk4tux** [comment]
What is the ./configure flag required to 'Not be a Debug Build' ? hence 
taking out the GUI tag Please..


or the code that can be remove to stop this 'label' ?


Nothing is shown for this that I can find in the wiki. Debug is well & 
good , but does it have to be painted on top ?


It makes the program look faulty straight up.....

**Comment by g4klx** [comment]
It really is not an issue.
