### ISSUE TITLE
Add an inactivity timer to the ircDDBGateway

### ISSUE THREAD

**Issue by pjao** [dl5di/OpenDV#125]
Hi!

Do you think that it be possible to add an inactivity timer to the ircDDBGateway?

This way, after some defined time it will disconnect from the reflector that someone my forgot connected.

It's very useful on multi mode repeaters.

Thanks,
Paulo - CT2JAY

**Comment by g4klx** [comment]
Such a timer has existed within the gateway for many years.

**Comment by pjao** [comment]
@g4klx Can you clarify what the parameter is? What's the timer name?
