### ISSUE TITLE
DstarRepeater with MMDVM 

### ISSUE THREAD

**Issue by iw9grl** [dl5di/OpenDV#131]
Hi
As DstarRepeater have the possibility to connect an MMDVM modem, I ask if there is a compatibility with the last version of MMDVM, I'm trying to connect a Nucleo board as MMDVM but seems doesn't work. Thank you

**Comment by phl0** [comment]
ircDDBGateway works with MMDVMHost independend of the modem used (MMDVM or DVmega etc.)

**Comment by iw9grl** [comment]
Hi
Thank you for your prompt answer. 
I'm trying to use the western dstar Pi image it had installed DstarRepeater +ircddbGateway, I ask to use the DstarRepeater instead of MMDVMHost

**Comment by phl0** [comment]
Oh sorry, my mistake. Haven't tried to use DStarRepeater with an MMDVM yet.

**Comment by iw9grl** [comment]
no problem !!! :)

**Comment by iw9grl** [comment]
I received these messages : 

I: 2017-05-30 20:56:22: Starting D-Star Repeater - 20151012
I: 2017-05-30 20:56:22: Using wxWidgets 2.8.12 on Linux 4.1.19-v7+ armv7l
I: 2017-05-30 20:56:22: Callsign set to "IW9GRL C", gateway set to "IW9GRL G", mode: 1, ack: 1, restriction: 0, RPT1 validation: 1, DTMF blanking: 1, Error reply: 1
I: 2017-05-30 20:56:22: Gateway set to 192.168.1.119:20010, local set to 192.168.1.100:20012, name set to "test"
I: 2017-05-30 20:56:22: Timeout set to 180 secs, ack time set to 500 ms
I: 2017-05-30 20:56:22: Beacon set to 10 mins, text set to "D-Star Repeater", voice set to 0, language set to 4
I: 2017-05-30 20:56:22: Announcement enabled: 0, time: 8 mins, record RPT1: "", record RPT2: "", delete RPT1: "", delete RPT2: ""
I: 2017-05-30 20:56:22: Modem type set to "MMDVM"
I: 2017-05-30 20:56:22: MMDVM, port: /dev/ttyACM0, RX invert: 0, TX invert: 0, PTT invert: 0, TX delay: 64 ms, RX level: 51%, TX level: 54%
I: 2017-05-30 20:56:24: MMDVM protocol version: 1, description: MMDVM 20170501 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) GitID #0000000
**E: 2017-05-30 20:56:24: Received a NAK to the SET_CONFIG command from the modem**
E: 2017-05-30 20:56:24: **Cannot open the D-Star modem**
I: 2017-05-30 20:56:24: Controller set to , config: 1, PTT invert: 0, active hang time: 0 ms
I: 2017-05-30 20:56:24: Output 1 = 0, output 2 = 0, output 3 = 0, output 4 = 0
I: 2017-05-30 20:56:24: Control: enabled: 0, RPT1: USERNAME, RPT2: PASSWORD, shutdown: STOP, startup: START, status1: , status2: , status3: , status4: , status5: , command1: REBOOT = sudo shutdown -r now, command2: CLOSE = sudo shutdown -h now, command3: UPDATEGW = klxupdate gateway -np, command4: UPDATERP = klxupdate repeater -np, command5: UPDATEHO = klxupdate hostfiles, command6:  = , output1: , output2: , output3: , output4:
I: 2017-05-30 20:56:24: Frame logging set to 0, in /root
I: 2017-05-30 20:56:40: D-Star Repeater is exiting

**Comment by vk4tux** [comment]
Something wrong with your Nucleo-64 setup, I loaded arduino header FW to 
a new prepared Nucleo-64 STM32F446RE here with good results, same FW


nucleardntoutp.hex 
<https://xa.yimg.com/df/mmdvm_builder/nucleardntoutp.hex?token=qDQT8gm-Et1eyu55T1K3eSFkwC3aWQwuR-ItgXzvyT5sPbLiq2XT2p9cx4LsSqH1FPHf5R0O47H6NILpwXnZoYzWWqwhe2CTYXyMIBSoGrYfiEPHgr9z2SCpUn5QVkvxMdCR3jud64mg&type=download>arduino 
header test

that i asked you to try, here and working ;

I: 2017-05-30 22:55:06: Starting D-Star Repeater - 20151012
I: 2017-05-30 22:55:06: Using wxWidgets 2.8.12 on Linux 3.10.92 armv7l
I: 2017-05-30 22:55:06: Callsign set to "VK4TUX B", gateway set to 
"VK4TUX G", mode: 0, ack: 2, restriction: 0, RPT1 validation: 0, DTMF 
blanking: 1, Error reply: 1
I: 2017-05-30 22:55:06: Gateway set to 192.168.1.166:20010, local set to 
192.168.1.166:20011, name set to ""
I: 2017-05-30 22:55:06: Timeout set to 180 secs, ack time set to 500 ms
I: 2017-05-30 22:55:06: Beacon set to 10 mins, text set to "D-Star 
Repeater", voice set to 0, language set to 0
I: 2017-05-30 22:55:06: Announcement enabled: 0, time: 8 mins, record 
RPT1: "", record RPT2: "", delete RPT1: "", delete RPT2: ""
I: 2017-05-30 22:55:06: Modem type set to "MMDVM"
I: 2017-05-30 22:55:06: MMDVM, port: /dev/ttyACM0, RX invert: 1, TX 
invert: 1, PTT invert: 0, TX delay: 100 ms, RX level: 80%, TX level: 40%
I: 2017-05-30 22:55:08: MMDVM protocol version: 1, description: MMDVM 
20170501 (D-Star/DMR/System Fusion/P25/RSSI/CW Id) GitID #9722c85
M: 2017-05-30 22:55:08: Found modem path of 
../../devices/usb.1/12000000.dwc3/xhci-hcd.2.auto/usb3/3-1/3-1.1/3-1.1:1.2/tty
M: 2017-05-30 22:55:08: Starting MMDVM Controller thread
I: 2017-05-30 22:55:08: Controller set to , config: 1, PTT invert: 0, 
active hang time: 0 ms
I: 2017-05-30 22:55:08: Output 1 = 0, output 2 = 0, output 3 = 0, output 
4 = 0
I: 2017-05-30 22:55:08: Control: enabled: 0, RPT1: , RPT2: , shutdown: , 
startup: , status1: , status2: , status3: , status4: , status5: , 
command1:  = , command2:  = , command3:  = , command4: = , command5:  = 
, command6:  = , output1: , output2: , output3: , output4:
I: 2017-05-30 22:55:08: Frame logging set to 0, in /home/odroid
M: 2017-05-30 22:55:08: Poll text set to "linux_mmdvm-20151012"
M: 2017-05-30 22:55:08: Starting the D-Star repeater thread


My dstarrepeater config ;

callsign=VK4TUX B
gateway=VK4TUX G
mode=0
ack=2
restriction=0
rpt1Validation=0
dtmfBlanking=1
errorReply=1
gatewayAddress=192.168.1.166
gatewayPort=20010
localAddress=192.168.1.166
localPort=20011
networkName=
modemType=MMDVM
timeout=180
ackTime=500
beaconTime=600
beaconText=D-Star Repeater
beaconVoice=0
language=0
announcementEnabled=0
announcementTime=480
announcementRecordRPT1=
announcementRecordRPT2=
announcementDeleteRPT1=
announcementDeleteRPT2=
controlEnabled=0
controlRPT1=
controlRPT2=
controlShutdown=
controlStartup=
controlStatus1=
controlStatus2=
controlStatus3=
controlStatus4=
controlStatus5=
controlCommand1=
controlCommand1Line=
controlCommand2=
controlCommand2Line=
controlCommand3=
controlCommand3Line=
controlCommand4=
controlCommand4Line=
controlCommand5=
controlCommand5Line=
controlCommand6=
controlCommand6Line=
controlOutput1=
controlOutput2=
controlOutput3=
controlOutput4=
controllerType=
serialConfig=1
pttInvert=0
activeHangTime=0
output1=0
output2=0
output3=0
output4=0
logging=0
windowX=438
windowY=546
dvapPort=
dvapFrequency=145500000
dvapPower=10
dvapSquelch=-100
gmskAddress=768
dvrptr1Port=
dvrptr1RXInvert=0
dvrptr1TXInvert=0
dvrptr1Channel=0
dvrptr1ModLevel=20
dvrptr1TXDelay=150
dvrptr2Connection=0
dvrptr2USBPort=
dvrptr2Address=127.0.0.1
dvrptr2Port=0
dvrptr2TXInvert=0
dvrptr2ModLevel=20
dvrptr2TXDelay=150
dvrptr3Connection=0
dvrptr3USBPort=
dvrptr3Address=127.0.0.1
dvrptr3Port=0
dvrptr3TXInvert=0
dvrptr3ModLevel=20
dvrptr3TXDelay=150
dvmegaPort=/dev/ttySAC0
dvmegaVariant=2
dvmegaRXInvert=0
dvmegaTXInvert=0
dvmegaTXDelay=150
dvmegaRXFrequency=445000000
dvmegaTXFrequency=445000000
dvmegaPower=100
mmdvmPort=/dev/ttyACM0
mmdvmRXInvert=1
mmdvmTXInvert=1
mmdvmPTTInvert=0
mmdvmTXDelay=100
mmdvmRXLevel=80
mmdvmTXLevel=40
soundCardRXDevice=
soundCardTXDevice=
soundCardRXInvert=0
soundCardTXInvert=0
soundCardRXLevel=1.0000
soundCardTXLevel=1.0000
soundCardTXDelay=150
soundCardTXTail=50
splitLocalAddress=
splitLocalPort=0
splitTXName0=
splitTXName1=
splitTXName2=
splitTXName3=
splitTXName4=
splitRXName0=
splitRXName1=
splitRXName2=
splitRXName3=
splitRXName4=
splitRXName5=
splitRXName6=
splitRXName7=
splitRXName8=
splitRXName9=
splitRXName10=
splitRXName11=
splitRXName12=
splitRXName13=
splitRXName14=
splitRXName15=
splitRXName16=
splitRXName17=
splitRXName18=
splitRXName19=
splitRXName20=
splitRXName21=
splitRXName22=
splitRXName23=
splitRXName24=
splitTimeout=0



FW config-h

/*
  *   Copyright (C) 2015,2016,2017 by Jonathan Naylor G4KLX
  *
  *   This program is free software; you can redistribute it and/or modify
  *   it under the terms of the GNU General Public License as published by
  *   the Free Software Foundation; either version 2 of the License, or
  *   (at your option) any later version.
  *
  *   This program is distributed in the hope that it will be useful,
  *   but WITHOUT ANY WARRANTY; without even the implied warranty of
  *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  *   GNU General Public License for more details.
  *
  *   You should have received a copy of the GNU General Public License
  *   along with this program; if not, write to the Free Software
  *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
  */

#if !defined(CONFIG_H)
#define  CONFIG_H

// Allow for the use of high quality external clock oscillators
// The number is the frequency of the oscillator in Hertz.
//
// The frequency of the TCXO must be an integer multiple of 48000.
// Frequencies such as 12.0 Mhz (48000 * 250) and 14.4 Mhz (48000 * 300) 
are suitable.
// Frequencies such as 10.0 Mhz (48000 * 208.333) or 20 Mhz (48000 * 
416.666) are not suitable.
//
// For 12 MHz
// #define EXTERNAL_OSC 12000000
// For 12.288 MHz
// #define EXTERNAL_OSC 12288000
// For 14.4 MHz
// #define EXTERNAL_OSC 14400000
// For 19.2 MHz
// #define EXTERNAL_OSC 19200000

// Allow the use of the COS line to lockout the modem
// #define USE_COS_AS_LOCKOUT

// Use pins to output the current mode
// #define ARDUINO_MODE_PINS

// For the original Arduino Due pin layout
// #define ARDUINO_DUE_PAPA

// For the ZUM V1.0 and V1.0.1 boards pin layout
// #define ARDUINO_DUE_ZUM_V10

// For the SQ6POG board
// #define STM32F1_POG

// For the SP8NTH board
// #define ARDUINO_DUE_NTH

// For ST Nucleo-64 STM32F446RE board
// #define STM32F4_NUCLEO_MORPHO_HEADER
#define STM32F4_NUCLEO_ARDUINO_HEADER

// Use separate mode pins to switch external filters/bandwidth for example
// #define STM32F4_NUCLEO_MODE_PINS

// Pass RSSI information to the host
// #define SEND_RSSI_DATA

// Use the modem as a serial repeater for Nextion displays
// #define SERIAL_REPEATER

#endif

**Comment by iw9grl** [comment]
Solved with the last DstarRepeater version available . 
Thank you to Adrian for the big support !!!!!

regards
Daniele IW9GRL
