### ISSUE TITLE
Need help: Compiling ircddbgateway failed

### ISSUE THREAD

**Issue by hb9pae** [dl5di/OpenDV#152]
Dear all 

Compiling ircddbgateway failed. Lib wx_baseu_net-3.0 missing.

I've compiled and installed wxWidgets-3.1.0  successfully.
Compiling package DStarrepeater works fine.

System: ALIX Board
OS: Debian weezy 
root@alix:/home/alix# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy

Error:
root@alix:/home/alix/OpenDV-all/ircDDBGateway# make
g++  -g -O2    -o ircddbgatewayd ircDDBGateway/ircddbgatewayd-IRCDDBGatewayAppD.o ircDDBGateway/ircddbgatewayd-IRCDDBGatewayStatusData.o ircDDBGateway/ircddbgatewayd-IRCDDBGatewayThread.o -L/usr/local/lib -pthread   -lwx_baseu-3.1  -lwx_baseu_net-3.0 libCommon.a libircDDB.a 
/usr/bin/ld: cannot find -lwx_baseu_net-3.0
collect2: error: ld returned 1 exit status
make: *** [ircddbgatewayd] Error 1

Any help appreciated!
Thanks, peter hb9pae

**Comment by phl0** [comment]
You need the wx3.0-headers installed. Not sure if those are available for wheezy though.

**Comment by hb9pae** [comment]
Thank you.
After installation of wx3.0-headers compilation worked.

73 de Peter HB9PAE
