### ISSUE TITLE
MMDVMHost 

### ISSUE THREAD

**Issue by pe1bzf** [dl5di/OpenDV#20]
Hi,

I run a raspberry with the Ircddbgateway software and a DVMega hybrid model.
Compiling MMDVMHost with no errors.
Starting MMDVMHost with edit MMDVM.ini file give this error:
Copyright (C) 2015 by Jonathan Naylor, G4KLX

M: 2015-12-26 09:34:25 MMDVMHost-20151222 is starting
M: 2015-12-26 09:34:25 Opening the MMDVM
E: 2015-12-26 09:34:35 Unable to read the firmware version after six attempts

How can i fix this ?

thanks

PE1BZF

**Comment by g4klx** [comment]
Hi

The reason it doesn't work is that the MMDVMHost is for use with the MMDVM modem. Please use the D-Star Repeater with the DVMega.

Jonathan. G4KLX

-----Original Message-----
