### ISSUE TITLE
ircddbgateway failed to build

### ISSUE THREAD

**Issue by N5QM** [dl5di/OpenDV#49]
The build platform is a RaspberryPi 2 running the Jessie based Raspian Lite image with all of the dependencies installed per the Wiki.  In addition, I had no issues compiling the dstarrepeater binary.

While attempting to compile ircddbgateway, the build fails with the following messages:

```
make[1]: Entering directory '/home/n5qm/OpenDV/ircDDBGateway/ircDDBGateway'
g++ -I../ircDDB -I../Common -O2 -march=armv7-a -mfpu=vfp -mfloat-abi=hard -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -Wno-psabi -DDATA_DIR='"/home/opendv/data"' -DBIN_DIR='"/usr/bin"' -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -DGPIO -pthread -I/usr/lib/arm-linux-gnueabihf/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -c IRCDDBGatewayApp.cpp
In file included from /usr/include/wx-3.0/wx/version.h:16:0,
                 from /usr/include/wx-3.0/wx/defs.h:193,
                 from /usr/include/wx-3.0/wx/wx.h:14,
                 from ../Common/HeaderData.h:22,
                 from ../Common/RepeaterProtocolHandler.h:22,
                 from ../Common/DummyRepeaterProtocolHandler.h:22,
                 from IRCDDBGatewayApp.cpp:19:
IRCDDBGatewayApp.cpp: In member function â€˜virtual bool CIRCDDBGatewayApp::OnInit()â€™:
/usr/include/wx-3.0/wx/chartype.h:238:44: error: â€˜LLOG_DIRâ€™ was not declared in this scope
             #define wxT(x) wxCONCAT_HELPER(L, x)
                                            ^
/usr/include/wx-3.0/wx/cpp.h:18:37: note: in definition of macro â€˜wxCONCAT_HELPERâ€™
 #define wxCONCAT_HELPER(text, line) text ## line
                                     ^
IRCDDBGatewayApp.cpp:83:15: note: in expansion of macro â€˜wxTâ€™
    m_logDir = wxT(LOG_DIR);
               ^
/usr/include/wx-3.0/wx/chartype.h:238:44: error: â€˜LCONF_DIRâ€™ was not declared in this scope
             #define wxT(x) wxCONCAT_HELPER(L, x)
                                            ^
/usr/include/wx-3.0/wx/cpp.h:18:37: note: in definition of macro â€˜wxCONCAT_HELPERâ€™
 #define wxCONCAT_HELPER(text, line) text ## line
                                     ^
IRCDDBGatewayApp.cpp:120:15: note: in expansion of macro â€˜wxTâ€™
   m_confDir = wxT(CONF_DIR);
               ^
Makefile:17: recipe for target 'IRCDDBGatewayApp.o' failed
make[1]: *** [IRCDDBGatewayApp.o] Error 1
make[1]: Leaving directory '/home/n5qm/OpenDV/ircDDBGateway/ircDDBGateway'
Makefile:12: recipe for target 'ircDDBGateway/ircddbgateway' failed
make: *** [ircDDBGateway/ircddbgateway] Error 2
```

**Comment by johnhays** [comment]
Your Makefile is missing some definitions.

-DCONF_DIR='"/etc"'   # Or other location
-DLOG_DIR='"/var/log/opendv"'  # Or other location

On Tue, Jan 12, 2016 at 7:55 PM, Robert Garcia, N5QM <
notifications@github.com> wrote:

> The build platform is a RaspberryPi 2 running the Wheezy based Raspian
> Lite image with all of the dependencies installed per the Wiki In addition,
> I had no issues compiling the dstarrepeater binary
>
> While attempting to compile ircddbgateway, the build fails with the
> following messages:
>
> make[1]: Entering directory '/home/n5qm/OpenDV/ircDDBGateway/ircDDBGateway'
> g++ -I/ircDDB -I/Common -O2 -march=armv7-a -mfpu=vfp -mfloat-abi=hard -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -Wno-psabi -DDATA_DIR='"/home/opendv/data"' -DBIN_DIR='"/usr/bin"' -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -DGPIO -pthread -I/usr/lib/arm-linux-gnueabihf/wx/include/gtk2-unicode-30 -I/usr/include/wx-30 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -c IRCDDBGatewayAppcpp
> In file included from /usr/include/wx-30/wx/versionh:16:0,
>                  from /usr/include/wx-30/wx/defsh:193,
>                  from /usr/include/wx-30/wx/wxh:14,
>                  from /Common/HeaderDatah:22,
>                  from /Common/RepeaterProtocolHandlerh:22,
>                  from /Common/DummyRepeaterProtocolHandlerh:22,
>                  from IRCDDBGatewayAppcpp:19:
> IRCDDBGatewayAppcpp: In member function â€˜virtual bool CIRCDDBGatewayApp::OnInit()â€™:
> /usr/include/wx-30/wx/chartypeh:238:44: error: â€˜LLOG_DIRâ€™ was not declared in this scope
>              #define wxT(x) wxCONCAT_HELPER(L, x)
>                                             ^
> /usr/include/wx-30/wx/cpph:18:37: note: in definition of macro â€˜wxCONCAT_HELPERâ€™
>  #define wxCONCAT_HELPER(text, line) text ## line
>                                      ^
> IRCDDBGatewayAppcpp:83:15: note: in expansion of macro â€˜wxTâ€™
>     m_logDir = wxT(LOG_DIR);
>                ^
> /usr/include/wx-30/wx/chartypeh:238:44: error: â€˜LCONF_DIRâ€™ was not declared in this scope
>              #define wxT(x) wxCONCAT_HELPER(L, x)
>                                             ^
> /usr/include/wx-30/wx/cpph:18:37: note: in definition of macro â€˜wxCONCAT_HELPERâ€™
>  #define wxCONCAT_HELPER(text, line) text ## line
>                                      ^
> IRCDDBGatewayAppcpp:120:15: note: in expansion of macro â€˜wxTâ€™
>    m_confDir = wxT(CONF_DIR);
>                ^
> Makefile:17: recipe for target 'IRCDDBGatewayAppo' failed
> make[1]: *** [IRCDDBGatewayAppo] Error 1
> make[1]: Leaving directory '/home/n5qm/OpenDV/ircDDBGateway/ircDDBGateway'
> Makefile:12: recipe for target 'ircDDBGateway/ircddbgateway' failed
> make: *** [ircDDBGateway/ircddbgateway] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dl5di/OpenDV/issues/49>.
>



-- 

------------------------------
John D. Hays
K7VE

PO Box 1223, Edmonds, WA 98020-1223
<http://k7ve.org/blog>  <http://twitter.com/#!/john_hays>
<http://www.facebook.com/john.d.hays>

**Comment by N5QM** [comment]
Ok, I have modified the file and I am building again.  I will submit a pull request with the changes assuming it finishes.

**Comment by N5QM** [comment]
It finished building, so I have submitted the pull request and will close this out.
