### ISSUE TITLE
Unmet dependencies on Debian Jessie.

### ISSUE THREAD

**Issue by iw0red** [dl5di/OpenDV#7]
Hi all,
I can't install dstarrepeater software because there is some issues:

root@IR0UAS:~# apt-get install dstarrepeater
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dstarrepeater : Depends: libwxbase2.8-0 (>= 2.8.10) but it is not installable
                 Depends: libwxgtk2.8-0 (>= 2.8.10) but it is not installable
                 Depends: libgnomeprint2.2-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@IR0UAS:~# 

Thanks you.

Marco IW0RED

**Comment by n8ohu** [comment]
Marco, it looks like the distribution you're using doesn't provide libwxgtk 2.8 or libgnomeprint2.2 at this time; later versions won't work.

**Comment by iw0red** [comment]
Thanks for the answer. 
It's time to eliminate wx...!
Marco IW0RED

**Comment by K2DLS** [comment]
Compiles fine on Debian 8.5 on Intel:

 dpkg --list | grep wx
ii  libwxbase3.0-0:amd64                                        3.0.2-1+b1                           amd64        wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.0-dev                                            3.0.2-1+b1                           amd64        wxBase library (development) - non-GUI support classes of wxWidgets toolkit
ii  libwxgtk3.0-0:amd64                                         3.0.2-1+b1                           amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
ii  libwxgtk3.0-dev                                             3.0.2-1+b1                           amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ development)
ii  wx-common                                                   3.0.2-1+b1                           amd64        wxWidgets Cross-platform C++ GUI toolkit (common support files)
ii  wx3.0-headers                                               3.0.2-1+b1                           amd64        wxWidgets Cross-platform C++ GUI toolkit (header files)

**Comment by iw0red** [comment]
.
