### ISSUE TITLE
Error comiling ircDDBGateway / IRCDDBMultiClient.cpp

### ISSUE THREAD

**Issue by phl0** [dl5di/OpenDV#71]
The current source code does not compile cleanly. I could not figure out what the mistake is but ircDDBGateay would just not compile. The errors are:

user@machine:~/OpenDV/ircDDBGateway$ make
make -C ircDDB
make[1]: Verzeichnis »/home/user/OpenDV/ircDDBGateway/ircDDB« wird betreten
g++ -g -O2 -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -DLOG_DIR='"/var/log"' -DCONF_DIR='"/etc"' -DDATA_DIR='"/usr/local/etc"' -DBIN_DIR='"/usr/local/bin"' -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -c IRCClient.cpp
g++ -g -O2 -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -DLOG_DIR='"/var/log"' -DCONF_DIR='"/etc"' -DDATA_DIR='"/usr/local/etc"' -DBIN_DIR='"/usr/local/bin"' -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -c IRCDDB.cpp
g++ -g -O2 -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -DLOG_DIR='"/var/log"' -DCONF_DIR='"/etc"' -DDATA_DIR='"/usr/local/etc"' -DBIN_DIR='"/usr/local/bin"' -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -c IRCDDBClient.cpp
g++ -g -O2 -Wall -Wno-non-virtual-dtor -Wno-strict-aliasing -DLOG_DIR='"/var/log"' -DCONF_DIR='"/etc"' -DDATA_DIR='"/usr/local/etc"' -DBIN_DIR='"/usr/local/bin"' -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -c IRCDDBMultiClient.cpp
In file included from IRCDDBMultiClient.cpp:23:0:
IRCDDBMultiClient.h: In constructor ‘CIRCDDBMultiClientQuery::CIRCDDBMultiClientQuery(const wxString&, const wxString&, const wxString&, const wxString&, const wxString&, IRCDDB_RESPONSE_TYPE)’:
IRCDDBMultiClient.h:41:15: error: ‘const class wxString’ has no member named ‘Clone’
   m_user(user.Clone()),
               ^
IRCDDBMultiClient.h:42:23: error: ‘const class wxString’ has no member named ‘Clone’
   m_repeater(repeater.Clone()),
                       ^
IRCDDBMultiClient.h:43:21: error: ‘const class wxString’ has no member named ‘Clone’
   m_gateway(gateway.Clone()),
                     ^
IRCDDBMultiClient.h:44:21: error: ‘const class wxString’ has no member named ‘Clone’
   m_address(address.Clone()),
                     ^
IRCDDBMultiClient.h:45:25: error: ‘const class wxString’ has no member named ‘Clone’
   m_timestamp(timestamp.Clone()),
                         ^
In file included from IRCDDBMultiClient.cpp:23:0:
IRCDDBMultiClient.h: In member function ‘void CIRCDDBMultiClientQuery::Update(const wxString&, const wxString&, const wxString&, const wxString&, const wxString&)’:
IRCDDBMultiClient.h:96:18: error: ‘const class wxString’ has no member named ‘Clone’
    m_user = user.Clone();
                  ^
IRCDDBMultiClient.h:97:26: error: ‘const class wxString’ has no member named ‘Clone’
    m_repeater = repeater.Clone();
                          ^
IRCDDBMultiClient.h:98:24: error: ‘const class wxString’ has no member named ‘Clone’
    m_gateway = gateway.Clone();
                        ^
IRCDDBMultiClient.h:99:28: error: ‘const class wxString’ has no member named ‘Clone’
    m_timestamp = timestamp.Clone();
                            ^
IRCDDBMultiClient.h:102:25: error: ‘const class wxString’ has no member named ‘Clone’
     m_address = address.Clone();
                         ^
IRCDDBMultiClient.h: In member function ‘wxString CIRCDDBMultiClientQuery::toString()’:
IRCDDBMultiClient.h:114:103: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
   return wxString::Format(wxT("%s %s %s %s %s"), m_user, m_repeater, m_gateway, m_address, m_timestamp);
                                                                                                       ^
IRCDDBMultiClient.h:114:103: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
IRCDDBMultiClient.h:114:103: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
IRCDDBMultiClient.h:114:103: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
IRCDDBMultiClient.h:114:103: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
IRCDDBMultiClient.cpp: In member function ‘virtual bool CIRCDDBMultiClient::receiveUser(wxString&, wxString&, wxString&, wxString&, wxString&)’:
IRCDDBMultiClient.cpp:282:33: error: ‘class wxString’ has no member named ‘Clone’
  userCallsign = item->getUser().Clone();
                                 ^
IRCDDBMultiClient.cpp:283:41: error: ‘class wxString’ has no member named ‘Clone’
  repeaterCallsign = item->getRepeater().Clone();
                                         ^
IRCDDBMultiClient.cpp:284:39: error: ‘class wxString’ has no member named ‘Clone’
  gatewayCallsign = item->getGateway().Clone();
                                       ^
IRCDDBMultiClient.cpp:285:31: error: ‘class wxString’ has no member named ‘Clone’
  address = item->getAddress().Clone();
                               ^
IRCDDBMultiClient.cpp:286:35: error: ‘class wxString’ has no member named ‘Clone’
  timeStamp = item->getTimestamp().Clone();
                                   ^
make[1]: *** [IRCDDBMultiClient.o] Fehler 1
make[1]: Verzeichnis »/home/user/OpenDV/ircDDBGateway/ircDDB« wird verlassen
make: *** [ircDDB/libircDDB.a] Fehler 2

**Comment by phl0** [comment]
@Just did a little bisect. First issues arise with commit a8d64f32f82ec0047f394514fcdabeb148b233dd by Geoffrey Merck.

**Comment by SpudGunMan** [comment]
Read the wiki for compile it's no longer using WX 2 on wx3 now update your dependency

**Comment by vk4tux** [comment]
http://vk4tux.duckdns.org/OD/DExtra_Hosts.txt

**Comment by F4FXL** [comment]
No problem compiling with wx3 ☺

**Comment by phl0** [comment]
Ok guys. Thank you for the information. I will close this issue and try to compile with WX3.
